import { Router } from "express";
import { newOrders,getOrders,newRider,upload,setPrice,loginRider,getProfile,updateOrders, deliveredOrders,loginManager,addManager} from "../controllers/userController.js";
import Auth from "../middlewares/auth.js";
import BossAuth from "../middlewares/bossAuth.js";
const router=Router();
router.post('/price',setPrice);
router.post('/orders',newOrders);
router.get('/rider/getOrders',getOrders);
router.patch('/rider/updateOrder',updateOrders);
router.post("/riders", upload.single("file"), newRider);
router.post("/rider/login",loginRider);
router.get("/rider/profile",Auth,getProfile);
router.get("/rider/deliveredOrders",Auth,deliveredOrders);
router.post("/manager/addManager",addManager);
router.post("/manager/login",loginManager);
export default router;